application:
  is_logistic_regression: True
  is_k_nearest_neighbor: False
  is_naive_bayes: False

binance_data_url: https://data.binance.vision/data/spot/monthly/klines

candle_parameters:          # All timestamps must be in milliseconds precision 
  start_ts: 1575147600000
  end_ts: 1680210000000
  symbol: ETHUSDT
  interval: 30m

labeling_parameters:
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9

normalization_parameters:
  standardization_window: 960
  standardization_limit: 4

training_parameters:
  training_size: 0.7             # Percantage value between 0 and 1
  validation_size: 0.2           # Percantage value between 0 and 1
  test_size: 0.1                 # Percantage value between 0 and 1

logistic_regression_parameters:
  learning_rate: 0.0001
  num_batch: 128                # Set to 1 to disable mini-batch
  num_epochs: 500
  threshold: 0.5
  stochastic: False
  regularization: True
  constant: 10
  class_weights: False
  transformation: ["RBF", "TRIG", "POLY"]   # ENUMS: {"TRIG", "POLY", "RBF"} | The transformation is applied from left to right sequentially

k_nearest_neighbor_parameters:
  k: [1, 20]
  oversample: False
  undersample: False


## Symbols ENUMS:
# Symbol Enumerations can be found here: https://data.binance.vision/?prefix=data/spot/monthly/klines/

## Interval ENUMS:
# KLINE_INTERVAL_1MINUTE = '1m'
# KLINE_INTERVAL_3MINUTE = '3m'
# KLINE_INTERVAL_5MINUTE = '5m'
# KLINE_INTERVAL_15MINUTE = '15m'
# KLINE_INTERVAL_30MINUTE = '30m'
# KLINE_INTERVAL_1HOUR = '1h'
# KLINE_INTERVAL_2HOUR = '2h'
# KLINE_INTERVAL_4HOUR = '4h'
# KLINE_INTERVAL_6HOUR = '6h'
# KLINE_INTERVAL_8HOUR = '8h'
# KLINE_INTERVAL_12HOUR = '12h'
# KLINE_INTERVAL_1DAY = '1d'
# KLINE_INTERVAL_3DAY = '3d'
# KLINE_INTERVAL_1WEEK = '1w'
# KLINE_INTERVAL_1MONTH = '1M'